# Generated by Django 3.1.4 on 2021-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rpassword',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
